name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install and build packages
        run: |
          echo "Installing and building 'app' package"
          cd app
          npm ci
          npm run build || true
          npm run lint || true
          npm run test || true
          cd ..
          if [ -d "travaid" ]; then
            echo "Installing and building 'travaid' package"
            cd travaid
            npm ci
            npm run build || true
            npm run lint || true
            npm run test || true
            cd ..
          fi
